services:
  my_mongo:
    image: mongo:latest
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: jjangu
        MONGO_INITDB_ROOT_PASSWORD: wow
    ports:
      - "27017:27017"
  your_mongo:
    image: mongo:latest
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: jjangu
        MONGO_INITDB_ROOT_PASSWORD: wow
    ports:
      - "27018:27017"

# https://hub.docker.com/_/redis
  my_redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  my_postgresql:
    container_name: my_postgresql
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: 'wow'
      POSTGRES_PASSWORD: 'wow'
      POSTGRES_DB: 'example'
    ports:
      - '5433:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql